# Generated by Django 4.2.6 on 2023-10-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_department', '0003_employee_department_alter_employee_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='manager_id',
            new_name='managerId',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='contact_number',
            new_name='contactNumber',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='date_of_joining',
            new_name='dateOfJoining',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='years_of_experience',
            new_name='yearsOfExperience',
        ),
    ]
