# Generated by Django 4.2.6 on 2023-10-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_department', '0004_rename_manager_id_department_managerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='yearsOfExperience',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
